version: "3.7"
services:
  python-grpc-server:
    container_name: ${SERVER_CONTAINER_NAME}
    image: ${SERVER_CONTAINER_IMAGE_NAME}:${SERVER_CONTAINER_VERSION}
    ports:
     - ${LOCALHOST_PORT}:${GRPC_PORT}
    environment:
      GRPC_PORT: ${GRPC_PORT}
    network_mode: default
  
  python-grpc-client:
    container_name: ${CLIENT_CONTAINER_NAME}
    image: ${CLIENT_CONTAINER_IMAGE_NAME}:${CLIENT_CONTAINER_VERSION}
    links:
      - ${SERVER_CONTAINER_NAME}
    environment:
      GRPC_PORT: ${GRPC_PORT}
      GRPC_HOST: ${SERVER_CONTAINER_NAME}
    network_mode: default
